export const establishmentTypes = [
  { name: 'Establecimiento de salud público', id: 'HEALTH_ESTABLISHMENT' },
  { name: 'Organizacion social', id: 'SOCIAL_ORGANIZATION' },
  { name: 'Organismo público', id: 'PUBLIC_INSTITUTION' },
  { name: 'Privado', id: 'PRIVATE_INSTITUTION' },
  { name: 'Establecimiento educativo', id: 'EDUCATIONAL_INSTITUTION' },
  { name: 'Otro', id: 'OTHER' },
];

export const countries = [
  { name: 'Argentina', id: 'Argentina' },
  { name: 'Bolivia', id: 'Bolivia' },
  { name: 'Brasil', id: 'Brasil' },
  { name: 'Chile', id: 'Chile' },
  { name: 'Colombia', id: 'Colombia' },
  { name: 'Costa Rica', id: 'Costa Rica' },
  { name: 'Ecuador', id: 'Ecuador' },
  { name: 'El Salvador', id: 'El Salvador' },
  { name: 'Guatemala', id: 'Guatemala' },
  { name: 'Haití', id: 'Haití' },
  { name: 'Honduras', id: 'Honduras' },
  { name: 'México', id: 'México' },
  { name: 'Nicaragua', id: 'Nicaragua' },
  { name: 'Panamá', id: 'Panamá' },
  { name: 'Paraguay', id: 'Paraguay' },
  { name: 'Perú', id: 'Perú' },
  { name: 'Puerto Rico', id: 'Puerto Rico' },
  { name: 'República Dominicana', id: 'República Dominicana' },
  { name: 'Uruguay', id: 'Uruguay' },
  { name: 'Venezuela', id: 'Venezuela' },
];
