name: Integration
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install node dependencies
        run: yarn install
      - name: Check format
        run: yarn fmt:check
